Facturas
zunkraz/PG-project pull request #219
Opened 2021-11-12 18:39 UTC by zunkraz

![image](https://user-images.githubusercontent.com/32313172/141518163-474c4d31-9c5f-4a50-a774-be4444035bd6.png)

Facturas para profesionales listo, faltan botones para cobrar , mejorar diseño etc etc

2021-11-12 19:03 UTC, svettorelo commented on api/src/controllers/functions/getInvoicesUser.js
> +    return ProfInvoice.find({professionalId: userId}).populate('customerId','username').populate('schedules','date'); } //:userId?as=prof
acá no dijimos date.shortcut?

2021-11-12 19:22 UTC, svettorelo commented on client/src/ApiReq/cart.js
> +        return  axios.get(`${BASIC_URL}/invoice/${customerId}?as=prof`)
acá se podría poner ya lo de la protección de rutas, tomando como ejemplo las otras funciones de ApiReq/
y lo sumamos al componente y a las rutas del back 📝

2021-11-12 21:56 UTC, svettorelo commented on client/src/Visuals/Components/Cart/PaymentsCartClient.jsx
> +                </th>
Sesiones

2021-11-12 21:57 UTC, svettorelo commented on client/src/Visuals/Components/Cart/PaymentsCartPro.jsx
> +        <h1>No hay Facturas que mostrar Profesional</h1>
creo que quedó el "Profesional" de más

2021-11-12 21:58 UTC, svettorelo requested changes
Todo ok
Pido los cambios para que agreguemos ya de una la protección (headers,token,etc)

2021-11-13 19:02 UTC, zunkraz commented on api/src/controllers/functions/getInvoicesUser.js
> +    return ProfInvoice.find({professionalId: userId}).populate('customerId','username').populate('schedules','date'); } //:userId?as=prof
listo

2021-11-13 20:24 UTC, maujpok approved these changes

2021-11-13 20:51 UTC, merged